# Generated by Django 4.2.29 on 2026-03-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rent_rate',
        ),
        migrations.AlterField(
            model_name='car',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale')], default='sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('buyer', 'Buyer')], default='buyer', max_length=10),
        ),
        migrations.DeleteModel(
            name='RentalBooking',
        ),
    ]
