# Generated by Django 4.2.29 on 2026-03-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0007_inquiry_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='discount_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='car',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(default='buyer', max_length=10),
        ),
        migrations.AlterField(
            model_name='discountevent',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
