# Generated by Django 4.2.29 on 2026-03-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0008_alter_car_discount_label_alter_car_discount_percent_and_more'),
        ('horizon', '0008_chat_models'),
    ]

    operations = [
    ]
