# Generated by Django 4.2.29 on 2026-03-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0009_chatsession_ticket'),
        ('horizon', '0009_merge_20260319_1614'),
    ]

    operations = [
    ]
