# Generated by Django 4.2.29 on 2026-03-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0010_merge_20260319_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
