# Generated by Django 4.2.29 on 2026-03-24 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0011_alter_chatsession_options_alter_car_discount_label_and_more'),
        ('horizon', '0011_alter_chatsession_options_and_more'),
    ]

    operations = [
    ]
