# Generated by Django 6.0.4 on 2026-04-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizon', '0024_dealershipsettings_footer_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='discountevent',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='events', to='horizon.car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='discount_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='car',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(default='buyer', max_length=10),
        ),
        migrations.AlterField(
            model_name='discountevent',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
